# Extracted with pattern: Conv2DWrapper\([^)]*, ([^,]+), [^,]+\);
# Prefix: std::vector<std::vector<seal::Plaintext>> 
# Suffix: _pts;
# Starting from line 6

std::vector<std::vector<seal::Plaintext>> tmp1_pts;
std::vector<std::vector<seal::Plaintext>> tmp6_pts;
std::vector<std::vector<seal::Plaintext>> tmp7_pts;
std::vector<std::vector<seal::Plaintext>> tmp12_pts;
std::vector<std::vector<seal::Plaintext>> tmp17_pts;
std::vector<std::vector<seal::Plaintext>> tmp22_pts;
std::vector<std::vector<seal::Plaintext>> tmp27_pts;
std::vector<std::vector<seal::Plaintext>> tmp32_pts;
std::vector<std::vector<seal::Plaintext>> tmp37_pts;
std::vector<std::vector<seal::Plaintext>> tmp42_pts;
std::vector<std::vector<seal::Plaintext>> tmp47_pts;
std::vector<std::vector<seal::Plaintext>> tmp52_pts;
std::vector<std::vector<seal::Plaintext>> tmp53_pts;
std::vector<std::vector<seal::Plaintext>> tmp58_pts;
std::vector<std::vector<seal::Plaintext>> tmp63_pts;
std::vector<std::vector<seal::Plaintext>> tmp68_pts;
std::vector<std::vector<seal::Plaintext>> tmp73_pts;
std::vector<std::vector<seal::Plaintext>> tmp78_pts;
std::vector<std::vector<seal::Plaintext>> tmp83_pts;
std::vector<std::vector<seal::Plaintext>> tmp88_pts;
std::vector<std::vector<seal::Plaintext>> tmp93_pts;
std::vector<std::vector<seal::Plaintext>> tmp98_pts;
std::vector<std::vector<seal::Plaintext>> tmp103_pts;
std::vector<std::vector<seal::Plaintext>> tmp108_pts;
std::vector<std::vector<seal::Plaintext>> tmp113_pts;
std::vector<std::vector<seal::Plaintext>> tmp114_pts;
std::vector<std::vector<seal::Plaintext>> tmp119_pts;
std::vector<std::vector<seal::Plaintext>> tmp124_pts;
std::vector<std::vector<seal::Plaintext>> tmp129_pts;
std::vector<std::vector<seal::Plaintext>> tmp134_pts;
std::vector<std::vector<seal::Plaintext>> tmp139_pts;
std::vector<std::vector<seal::Plaintext>> tmp144_pts;
std::vector<std::vector<seal::Plaintext>> tmp149_pts;
std::vector<std::vector<seal::Plaintext>> tmp154_pts;
std::vector<std::vector<seal::Plaintext>> tmp159_pts;
std::vector<std::vector<seal::Plaintext>> tmp164_pts;
std::vector<std::vector<seal::Plaintext>> tmp169_pts;
std::vector<std::vector<seal::Plaintext>> tmp174_pts;
std::vector<std::vector<seal::Plaintext>> tmp179_pts;
std::vector<std::vector<seal::Plaintext>> tmp184_pts;
std::vector<std::vector<seal::Plaintext>> tmp189_pts;
std::vector<std::vector<seal::Plaintext>> tmp194_pts;
std::vector<std::vector<seal::Plaintext>> tmp199_pts;
std::vector<std::vector<seal::Plaintext>> tmp204_pts;
std::vector<std::vector<seal::Plaintext>> tmp205_pts;
std::vector<std::vector<seal::Plaintext>> tmp210_pts;
std::vector<std::vector<seal::Plaintext>> tmp215_pts;
std::vector<std::vector<seal::Plaintext>> tmp220_pts;
std::vector<std::vector<seal::Plaintext>> tmp225_pts;
std::vector<std::vector<seal::Plaintext>> tmp230_pts;
std::vector<std::vector<seal::Plaintext>> tmp235_pts;
std::vector<std::vector<seal::Plaintext>> tmp240_pts;
std::vector<std::vector<seal::Plaintext>> tmp245_pts;